server:
  tomcat:
    uri-encoding: UTF-8
  port: 12801

spring:
  datasource:
    url: jdbc:mysql://192.168.1.201:3306/user?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    password: Admin123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
  redis:
    pool:
     max-active: 300
     min-idle: 0
     max-wait: 10000
     max-idle: 100
     timeout: 5000
    host: 127.0.0.1
    password:
    database: 6
    port: 6379

SMSService:
  host: http://192.168.1.201:12804
HXService:
  host: http://192.168.1.201:12802
ZaoKinService:
  host: http://192.168.1.201:12805