server:
  tomcat:
    uri-encoding: UTF-8
  port: 7008

spring:
  datasource:
    url: jdbc:mysql://rm-wz9o958tqrkorqyimfo.mysql.rds.aliyuncs.com:3306/wz-test?useUnicode=true&useSSL=false&allowMultiQueries=true
    username: wztest
    password: aiforever123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  redis:
    pool:
     max-active: 300
     min-idle: 0
     max-wait: 10000
     max-idle: 100
     timeout: 5000
    host: 127.0.0.1
    password:
    database: 6
    port: 6379

gatewayService:
   host: 127.0.0.1:12707